### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by epinna** [epinna/weevely3#1]
- [ ] Integrate weevely3 as Metasploit payload
- [ ] Allow chains of session to bounce between multiple weevely agents

**Comment by BlackEyes250** [comment]
hi there i've just created a backdoor and logged in, but when i do the "ls" command to list the files
i get this error
[-][module] Error, module execution triggered error ''NoneType' object has no attribute 'send''

what can i do?

**Comment by AppoPro** [comment]
Will be good to make weevely Shell Manager
