### ISSUE TITLE
Unsupported operand type(s) for +=: 'NoneType' and 'list'

### ISSUE THREAD

**Issue by mmomasters** [epinna/weevely3#101]
Trying to give a wordlist for bruteforce_sql but error all the time..

**Comment by zeckdude** [comment]
Same here :(

**Comment by zeckdude** [comment]
@epinna Do you know anything about this?

**Comment by zeckdude** [comment]
I tried it with both v3.6.2 and 3.7.0 and both have the same problem

**Comment by epinna** [comment]
Please try now.
