### ISSUE TITLE
Python 3 Port

### ISSUE THREAD

**Issue by eltouco72** [epinna/weevely3#102]
Hi,

Currently Weevely does not work under Python3 (I tried i got a lot of import error messages)

Is a port to Python3 scheduled ? (I don't know Python enough to contribute to this)
Since some linux distribution now include Python3 by default and not Python2 it could be a useful feature

thanks

**Comment by epinna** [comment]
Hello,

There is no plan to port it to Python 3 any time soon, but I'll keep this open for future development.

Thanks

**Comment by OwenChia** [comment]
Hi @eltouco72,

I'm working on an [py3k porting](https://github.com/OwenChia/weevely3).

It's still in a very early stage, but the command like `ls`, `cat` should be work now.
If you really need python3 version and not in a very serious case, maybe you can give it a try.

I'm not a master in python, and not sure if I fully understand the code, so it's risky.



Many thanks for @epinna developed such a great program.

**Comment by samueloph** [comment]
I just tried helping with this at https://github.com/epinna/weevely3/pull/119

**Comment by epinna** [comment]
It has been ported to Python 3, feel free to try it.

https://github.com/epinna/weevely3/releases/tag/v4.0.0

**Comment by epinna** [comment]
Dear @samueloph, I release a version that fixes the pretty annoying issue #122 , you might want to package this when you have time.

**Comment by samueloph** [comment]
@epinna Just uploaded 4.0.1-1, should hit the repositories soon, thanks for the heads up :)
