### ISSUE TITLE
what is 'image not found'

### ISSUE THREAD

**Issue by bigblackhat** [epinna/weevely3#104]
hi,first of all,I really like your project,and I'm a Chinese,my English is no good,I used the dictionary.
I have an error,my terminal return the following error message:
```
python weevely.py
Traceback (most recent call last):
  File "weevely.py", line 2, in <module>
    from core.terminal import Terminal
  File "/Users/diana.wang/Downloads/weevely3-master/core/terminal.py", line 9, in <module>
    import readline
ImportError: dlopen(/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so, 2): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so
  Reason: image not found
```
I already install modules by your requirement.txt,I don't no why was that, can you help me?

**Comment by epinna** [comment]
I cant' reproduce it, I guess it's some error with the `readline` installed by your Python installed with homebrew.

I read [here](https://github.com/Homebrew/homebrew-core/issues/5799) the suggest to run `brew upgrade`, did you try that?
