### ISSUE TITLE
Remove readline from requirements.txt

### ISSUE THREAD

**Issue by exploide** [epinna/weevely3#113]
This might be quite the opposite of #55 but I would like to propose removing `readline` from `requirements.txt`.

I had trouble installing this module on a recent Fedora machine and the readme for `readline` (https://pypi.org/project/readline/) claims that "THIS PACKAGE IS DEPRECATED".

Instead, one should use `gnureadline`, which installs correctly. However, the readme of `gnureadline` (https://pypi.org/project/gnureadline/) explains "do you really need this package in 2019? You typically don’t".

Instead, one should take a look at the standard library `readline` module (https://docs.python.org/2.7/library/readline.html), which apparently has the same module interface and looks compatible.

In order to avoid troubles while installing deprecated third party `readline` module, I propose to remove this from `requirements.txt`.

**Comment by epinna** [comment]
That sounds reasonable, thanks.
