### ISSUE TITLE
Backdoor communication failed - weevely 3.7.0

### ISSUE THREAD

**Issue by ech0yg** [epinna/weevely3#114]
Hi, when I am trying the weevely 3.7 to connect backdoor, and I do not get the following:

root@hl-test:/usr/tools/weevely3# ./weevely.py http://183.2.x.x:8080/agent.php mypassword
/usr/tools/weevely3/core/sessions.py:219: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sessiondb = yaml.load(open(dbpath, 'r').read())

[+] weevely 3.7.0

[+] Target:	183.2.x.x:8080
[+] Session:	/root/.weevely/sessions/183.2.x.x/agent_0.session

[+] Browse the filesystem or execute commands starts the connection
[+] to the target. Type :help for more information.

weevely> uname -a
[!][terminal] Backdoor communication failed, check URL availability and password
weevely> :set debug true
debug = true
weevely> uname -a
[D][php] PHP setup failed 
[!][terminal] Backdoor communication failed, check URL availability and password
weevely> ls
[D][php] PHP setup failed 
[!][terminal] Backdoor communication failed, check URL availability and password

The network is ok:
![image](https://user-images.githubusercontent.com/45033430/64591937-82f77780-d3dd-11e9-955c-03b9712e7745.png)

**Comment by ech0yg** [comment]
Sorry, the problem is caused by the php environment.

**Comment by l0calgh05t** [comment]
@ech0yg maaaaan.... Why dont you just shared how you solved your problem?

**Comment by xulicn** [comment]
May I ask how this problem was solved?

**Comment by theGreyOnceler** [comment]
I had similar issue.

downloading version weevely3-4.0.0 seemed to be able to connect to the payload, there must have been a change causing error connecting to older generated payloads.
