### ISSUE TITLE
Weevely with TTY

### ISSUE THREAD

**Issue by eltouco72** [epinna/weevely3#116]
Hello there,

is it possible that weevely has a "TTY feature" in the future ?
currently command like su ou sudo does not work because those commande can not be run from terminal
and commande like python -c 'import pty; pty.spawn("/bin/bash")'  does not work as well.

Cheers and congratulation for the good work !

**Comment by epinna** [comment]
Nope, it's not possible.

I advise to use a backdoor module such as `:backdoor_reversetcp` or `:backdoor_tcp` and then run `python -c 'import pty; pty.spawn("/bin/bash")` to spawn the pty.
