### ISSUE TITLE
LS command crash!!

### ISSUE THREAD

**Issue by BlackEyes250** [epinna/weevely3#12]
hi there i've just created a backdoor and logged in, but when i do the "ls" command to list the files
i get this error
[-][module] Error, module execution triggered error ''NoneType' object has no attribute 'send''

what can i do?

**Comment by BlackEyes250** [comment]
also when i do :backdoor_tcp

**Comment by epinna** [comment]
Could you please re-run weevely, and execute `:set debug True` before to run the crashing commands?

**Comment by BlackEyes250** [comment]
now it work's , it was a php bug ;)
