### ISSUE TITLE
Manage missing php binary required by the 'generate' command

### ISSUE THREAD

**Issue by xorond** [epinna/weevely3#121]
hi,

i am running the latest version 4.0.0 with py3.8.1

trying to generate a simple agent

```
$ weevely generate test test
Exiting: Error with obfuscator template '/usr/share/weevely/bd/obfuscators/obfusc1_php.tpl': cannot use a bytes pattern on a string-like object
```

```
$ python --version
Python 3.8.1
```

**Comment by xorond** [comment]
problem solved. you need to have `php` installed on your system for this to work.

**Comment by epinna** [comment]
Thanks for the issue, I'll add the code to manage this scenario.

**Comment by epinna** [comment]
It has been fixed on master.
