### ISSUE TITLE
cd command does not work anymore

### ISSUE THREAD

**Issue by eltouco72** [epinna/weevely3#122]
Hi,

since I upgraded weevely to the last release 4.0.0 the cd command does not work anymore
 cd .. or cd directory we stay on the directory where the shell is.

tried on different target with different PHP versions, the result is the same
I also upgraded the weevely dependencies to the lstest version using
sudo pip3 install -r requirements.txt --upgrade

**Comment by epinna** [comment]
Thank you for spotting this. Please give it a try before a release the next version.

**Comment by eltouco72** [comment]
thanks for the quick fix !
It now works again
