### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. when i run: weevely http://host/backdoor.php password

### ISSUE THREAD

**Issue by jordantsap** [epinna/weevely3#123]
Weevely is connecting as it should but i get this
/usr/share/weevely/core/sessions.py:219: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sessiondb = yaml.load(open(dbpath, 'r').read())

Is it me or the remote php version as mentioned in other issue??
Irun with php7.3 or above and the remote running 5.6 i think

**Comment by epinna** [comment]
You're not using the last version, clone this repo or download the latest [one](https://github.com/epinna/weevely3/releases/latest).
