### ISSUE TITLE
Module Erorr

### ISSUE THREAD

**Issue by thecowmilk** [epinna/weevely3#127]
Hi guys, I was using this python script and I ran into a `Module Error` problem, more like:
```
Traceback (most recent call last):
  File "./weevely.py", line 2, in <module>
    from core.terminal import Terminal
ModuleNotFoundError: No module named 'core'
```
and even in the websites like stackoverflow couldn't answer my question. I'm running this script in a Ubuntu 18.04 LTS the latest version(I mean, I installed the 18.04 LTS before the 19 will be dropped but I have kept it up-to-date using `apt update` and `apt upgrade -- dist-upgrade`.

I tried to install it even with `pip` but didn't worked. Thanks in advance guys :D

**Comment by epinna** [comment]
Did you download weevely from this repository or did you install it through apt?
