### ISSUE TITLE
PHP failed

### ISSUE THREAD

**Issue by sumo2001** [epinna/weevely3#129]
> I uninstalled and re installed php but no use!!

root@sumo:~# weevely http://192.168.55.105/DVWA/hackable/uploads/arigato allmight
 
[+] weevely 4.0.1

[+] Target:	192.168.55.105
[+] Session:	/root/.weevely/sessions/192.168.55.105/arigato_0.session

[+] Browse the filesystem or execute commands starts the connection
[+] to the target. Type :help for more information.

weevely> ?
PHP setup failed 
Backdoor communication failed, check URL availability and password
weevely>

**Comment by epinna** [comment]
That's not about your installation of PHP, the message means that weevely can't execute PHP code on the target. As the message says, double-check URL is reachable and password is correct.
