### ISSUE TITLE
How to set up additional headers in weevely for custom cookies.

### ISSUE THREAD

**Issue by FaizanNehal** [epinna/weevely3#137]
I am so sorry if this is a basic question, but I am new to this field and I cannot find answer to this question anywhere else.
I have uploaded a weevely backdoor on to a website, and I have the path to my backdoor. the only problem is that in order to open the path to gain access to the backdoor I need tobe logged in on website.
How can I solve this issue and gain access to my backdoor file with weevely? I think I need to add my session cookies but where should I add them? Is it possible in weevely to do this?

**Comment by epinna** [comment]
Hello,

You can customize your config.py, see the comments here.

https://github.com/epinna/weevely3/blob/master/core/config.py#L26
