### ISSUE TITLE
Weevely communication error

### ISSUE THREAD

**Issue by comix4k** [epinna/weevely3#139]
![helkpgit](https://user-images.githubusercontent.com/69500838/89865122-25365700-db7b-11ea-9bb0-ad0125bbfd0e.PNG)

I've already looked at the other people having the same error but no fix.

if anyone could help me with this communication error that would be great thx :]

Also, I'm new, I'm trying to upload a weevely backdoor to dvwa but I am a beginner so I am not smart at all :]

**Comment by epinna** [comment]
As per the error, it's probably the unreachable URL or you're using a wrong password.
