### ISSUE TITLE
.php.jpg doesn't work

### ISSUE THREAD

**Issue by fantomcheg** [epinna/weevely3#142]
python3 weevely.py http://10.8.0.1:60769/upload/weevely2.php.jpg 123

[+] weevely 4.0.1

[+] Target:     10.8.0.1:60769
[+] Session:    /home/kevin/.weevely/sessions/10.8.0.1/weevely2.php_0.session

[+] Browse the filesystem or execute commands starts the connection
[+] to the target. Type :help for more information.

weevely> ls
The request triggers the error 405, please verify running code
Backdoor communication failed, check URL availability and password

Please help

**Comment by epinna** [comment]
Try to run `:set debug True` and debug your issue.

**Comment by fantomcheg** [comment]
I've done it.

weevely> system_info 
[ERR] Not Allowed [405]
The request triggers the error 405, please verify running code
PHP setup failed 
Backdoor communication failed, check URL availability and password
weevely> :system_info 
[ERR] Not Allowed [405]
The request triggers the error 405, please verify running code
PHP setup failed 
Backdoor communication failed, check URL availability and password
weevely>

**Comment by b4rdia** [comment]
Hi, I know this issue is closed and old, but I have the exact problem when I try to connect to a shell with .php.jpg extension,
```
weevely> system_info
[ERR] Not Allowed [405]
The request triggers the error 405, please verify running code
PHP setup failed
Backdoor communication failed, check URL availability and password
```
no luck so far, I wanted to ask if you were able to fix this issue? @fantomcheg
