### ISSUE TITLE
it could not read the local file path 

### ISSUE THREAD

**Issue by alauthor** [epinna/weevely3#143]
Error loading file '/Desktop/wordlist.txt': [Errno 2] No such file or directory: '/Desktop/wordlist.txt'
the file should be on server I connect with not with the machine I use 
how could I solve this problem ?

**Comment by Danielvdd1** [comment]
Do you use :bruteforce_sql?
It uses a wordlist from the local machine, not the server.

If the problem is that the wordlist is on the server, you can for example download the wordlist with :file_download.

**Comment by carlosalbertocruz** [comment]
I'm used this command:  :file_download index.php (remote local) /root/Desktop (local path), but I received this error
Error loading file '/root/FileUpload': [Errno 13] Permission denied: '/root/Desktop '

**Comment by Danielvdd1** [comment]
Probably because you/weevely don't have permission to the /root directory. Use a /home user folder instead.
(Or run weevely with sudo. I have not tested this.)
