### ISSUE TITLE
PHP setup failed, but I sure the environment is ok

### ISSUE THREAD

**Issue by WillianWang2025** [epinna/weevely3#149]
[root@rz-5 weevely3]# python weevely.py http://172.xx.xx.xx/agent.php password

[+] weevely 4.0.1

[+] Target:     172.xx.xx.xx
[+] Session:    /root/.weevely/sessions/172.xx.xx.xx/agent_0.session

[+] Browse the filesystem or execute commands starts the connection
[+] to the target. Type :help for more information.

weevely> :set debug true
debug = true
weevely> ls
PHP setup failed
Backdoor communication failed, check URL availability and password

And I test the env by a phpinfo():
<?php
phpinfo();
?>
I can access the page, and shows the correct result?

///////////////////////

why php setup failed ?

**Comment by epinna** [comment]
Sorry but I can't debug your PHP environment.
