### ISSUE TITLE
The script cannot run correctly in PHP 8th.

### ISSUE THREAD

**Issue by wyb-777** [epinna/weevely3#150]
After creating a web environment with LAMPP, PHP 8th, I uploaded a generated webshell and tried to make a connection as usual. But there's something wrong, with some warnings as follows.

`The remote backdoor request triggers an error 500;  
Backdoor communication failed, check URL availability and password
`

I made some tests based on other PHP versions, on which weevely ran well. As a consequence, I guess the latest version is incompatible with PHP 8th. Looking forward to making some improvements.

**Comment by epinna** [comment]
Tracked in #151
