### ISSUE TITLE
File edit functionality not working

### ISSUE THREAD

**Issue by emilyanncr** [epinna/weevely3#152]
Hi there.  Great tool.  
The file editor seems to not be working.  I'm getting the error " "Error, module execution triggered error 'binary mode doesn't take an encoding argument'.  Can you please advise?  Thanks.
![weevley editor not working](https://user-images.githubusercontent.com/8577656/145736715-c841ba4f-e4e9-474c-849e-f4907b28ef9f.png)

**Comment by ZanyMonk** [comment]
Cannot reproduce, may have been fixed already.
