### ISSUE TITLE
ModuleNotFoundError: No module named 'readline' AND  'gnureadline'

### ISSUE THREAD

**Issue by ErrorMySQL** [epinna/weevely3#178]
` C:\Users\Windows\Desktop\weevely3>python weevely.py
`

Traceback (most recent call last):
  File "C:\Users\Windows\Desktop\weevely3\core\terminal.py", line 11, in <module>
    import gnureadline as readline
ModuleNotFoundError: No module named 'gnureadline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Windows\Desktop\weevely3\weevely.py", line 14, in <module>
    from core.terminal import Terminal
  File "C:\Users\Windows\Desktop\weevely3\core\terminal.py", line 13, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

`C:\Users\Windows\Desktop\weevely3>pip install gnureadline
`
DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\ghauri-1.2.3-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..

DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\pluginbase-1.0.1-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\pysocks-1.7.1-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\userefuzz-2.2.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\wafw00f-2.2.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Collecting gnureadline
  Using cached gnureadline-8.1.2.tar.gz (3.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      Error: this module is not meant to work on Windows (try pyreadline instead)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

`C:\Users\Windows\Desktop\weevely3>pip install readline
`

DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\ghauri-1.2.3-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..

DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\pluginbase-1.0.1-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\pysocks-1.7.1-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\userefuzz-2.2.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\Windows\appdata\local\programs\python\python311\lib\site-packages\wafw00f-2.2.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Collecting readline
  Using cached readline-6.2.4.1.tar.gz (2.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: this module is not meant to work on Windows
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

`C:\Users\Windows\Desktop\weevely3>
`

**Comment by ZanyMonk** [comment]
Weevely does not support Windows, since it relies on `readline`, which is based on GNU `readline`.
Weevely should work fine in a [WSL](https://learn.microsoft.com/en-us/windows/wsl/) too, maybe you'll find this easier.
