### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AppoPro** [epinna/weevely3#18]
How about logs weevely 3 are stealth on system ?
PS. Will be good to make module ( Clear logs)

**Comment by epinna** [comment]
Are you talking about the server-side or client-side logs?

**Comment by AppoPro** [comment]
server-side

**Comment by epinna** [comment]
That's a good idea, but I would implement it in a more generic way. I'm thinking to implement a `:file_grep` module which you can run as

`:file_grep 10.0.1.1 /home/user/log/httpd.log`

To check if your IP is logged and

`:file_grep -v 10.0.0.1 /home/user/log/httpd.log -out /home/user/log/http.log.clean`
`mv /home/user/log/http.log.clean /home/user/log/httpd.log`

Whether you want to filter out your IP from the log files. I'll implement it as soon as I have some time. Thanks for the hint.

**Comment by epinna** [comment]
I added the `-v` and `-output` options to `file_grep` modules, which can help to clear tracks from the target system log files.

Read the [tutorial](https://github.com/epinna/weevely3/wiki/Clean-IP-address-from-logs) for a quick example. Thanks for the precious hint :)
