### ISSUE TITLE
Fix Module 

### ISSUE THREAD

**Issue by tarunsagarpandey** [epinna/weevely3#184]
In weevely.py

Import generate needed 

Core/generate.py

Import Template needed 

🙂

**Comment by tarunsagarpandey** [comment]
> https://github.com/epinna/weevely3/blob/445bd88be1a7ae2a1aaa34b88a38a92786e56b84/weevely.py#L7
> https://github.com/epinna/weevely3/blob/445bd88be1a7ae2a1aaa34b88a38a92786e56b84/core/generate.py#L5
> 
> :slightly_smiling_face:



Bro I know there's it already  but then also error coming 
 Anyways look on it ![IMG_20240421_171612.jpg](https://github.com/epinna/weevely3/assets/143919121/4a39f822-eeca-4fd6-bc60-d2749cc927aa)

**Comment by tarunsagarpandey** [comment]
> https://github.com/epinna/weevely3/blob/445bd88be1a7ae2a1aaa34b88a38a92786e56b84/weevely.py#L7
> https://github.com/epinna/weevely3/blob/445bd88be1a7ae2a1aaa34b88a38a92786e56b84/core/generate.py#L5
> 
> :slightly_smiling_face:




I'm trying to say   can qst format changes like 2nd then maybe it's work 🤷🏻‍♂️ i don't know more i just simply said 🤷🏻‍♂️ 

; from core ;  is deleted Only import generate is there 🤷🏻‍♂️

/ 1st format 

import sys
from core import generate

/2nd format 

import sys
import generate

**Comment by ZanyMonk** [comment]
![image](https://github.com/epinna/weevely3/assets/3920186/20cbb216-9be2-4b2d-a391-852e76c3ba76)

This line indicates you don't have the required dependencies installed on your system.

Try running `pip install -r requirements.txt`, or install the libs mentioned in `requirements.txt` manually using your package manager.
