### ISSUE TITLE
Clean IP address from logs error

### ISSUE THREAD

**Issue by AppoPro** [epinna/weevely3#21]
When i try "grep access.log -v 174.122.136.104 -output cleaned.log"
I have this error "grep: invalid option -- 't'"

**Comment by AppoPro** [comment]
I found error. Need to use the module GREP not GREP of the system. Will be go to specific it in Tutorial.

**Comment by AppoPro** [comment]
Close please.THX

**Comment by epinna** [comment]
The example runs "in a server which which does not allow shell commands execution", which is not your case. Closed.

**Comment by patzor** [comment]
or just type in

grep access.log -v 174.122.136.104 > cleaned.log
mv cleaned.log access.log
