### ISSUE TITLE
New Module file_infect

### ISSUE THREAD

**Issue by AppoPro** [epinna/weevely3#23]
Will be good to make file_infect module.
file_infect will secure integrate shell in php file.

**Comment by epinna** [comment]
I already thought about this. It's not trivial to add executable code, inside of the executable part of an existing script avoiding any condition that would kill the script before (imagine a die() placed in some if before). The only safe solution would be to prepend it in the file header, but this is not so useful for a PHP code that should be hidden somewhere inside of script internals. I will not implement this, I think that `:file_edit` module is fast enough if someone want to infect an existing script.
