### ISSUE TITLE
sqlmap Issue

### ISSUE THREAD

**Issue by KingBBBBBBB** [epinna/weevely3#26]
Hello i have a question insted of testing all the possible attacked using sqlmap is there any way to test a vulnerable server using a perticular type of attack only... for ex. i only want to attack a webserver with PostgreSQL stacked conditional-error blind queries ?? is there any way to do so....

**Comment by epinna** [comment]
This is not a place to ask question about sqlmap, that is not related in any way with weevely - I suggest you to ask this to some other page related to that.
