### ISSUE TITLE
how to use custom HTTP headers

### ISSUE THREAD

**Issue by toby57** [epinna/weevely3#29]
such as X-Forwarded-For, Cookie

**Comment by epinna** [comment]
Hi Toby,

See the `additional_headers` variable in [core/config.py](https://github.com/epinna/weevely3/blob/master/core/config.py).

You can declare smth like

```
additional_headers = [
   ( 'X-Forwarded-For', '10.0.0.1' ),
   ( 'Cookie', 'FIELD=value; FIELD2=value2' ),
]
```

I hope it can helps.
