### ISSUE TITLE
ImportError: No module named mako.template

### ISSUE THREAD

**Issue by davidepiantella** [epinna/weevely3#3]
.....~/weevely3$ python weevely.py
Traceback (most recent call last):
  File "weevely.py", line 10, in <module>
    from core.terminal import Terminal
  File "weevely3/core/terminal.py", line 6, in <module>
    from core.module import Status
  File "weevely3/core/module.py", line 14, in <module>
    from core.vectorlist import VectorList
  File "weevely3/core/vectorlist.py", line 15, in <module>
    from core.vectors import Os
  File "weevely3/core/vectors.py", line 11, in <module>
    from mako.template import Template
ImportError: No module named mako.template

**Comment by msiraj83** [comment]
@epinna ... thanks ... it work for me...

**Comment by ycjcl868** [comment]
me too, but not work for me...

**Comment by Pulat7484** [comment]
Great thanks for help...!
It works!

**Comment by denisrosas** [comment]
5 years later and your solution still works =)
I'm compiling AOSP for raspberry and got the same error. Thanks!

**Comment by borahan951** [comment]
No module named request

**Comment by fear-less-captain** [comment]
It not working for me. is there any other solution

**Comment by fear-less-captain** [comment]
epinna Its not working for me is there any other solution.

**Comment by sameerppradhan** [comment]
This solution still saved my time again after all these years. Thank you.:)
