### ISSUE TITLE
zip packaging?

### ISSUE THREAD

**Issue by deepgray** [epinna/weevely3#35]
was able to generate the .php file, but through the admin webfront, i have to upload a .zip file that is a directory structure with additional files.

any suggestions on how to create this?

**Comment by epinna** [comment]
This is unclear, please elaborate

**Comment by deepgray** [comment]
i was looking at a wordpress 3.5.1 configuration. on teh admin page there is a plugin install where you select a zip file, install, then activate it. examining the plugins from wordpress, they are a directory structure that has been zipped. there is apparently additional hooks, etc for the admin area within the structure. i ended up generating a php backdoor with msvenom, then uploading it the web root via the installed wp_FileManager plugin from the wordpress open repository.
