### ISSUE TITLE
Weevely and custom cookies

### ISSUE THREAD

**Issue by backtr4ck** [epinna/weevely3#38]
I have this scenario:

Weevely is uploaded in my test site in which I have to login to upload stuff. The only way I can access the php is if I use the logged in user cookie. Tried to set it in config.py under "additional_headers" but I have no idea how to do it right. How can I do this?

**Comment by backtr4ck** [comment]
this is how I set it up

`additional_headers = [ 
	( 'Cookie', 'dASP.NET_SessionId=d133pgtmjnox2qytlfrkk3go' )
]`

when I try it, weevely says
`[!][terminal] Backdoor communication failed: please check URL reachability and password`
(password is correct)

**Comment by epinna** [comment]
Hello,

Yes should work in that way. Do you remember if you created the PHP agent with weevely version 3.x or with a previous version?

**Comment by backtr4ck** [comment]
v3.2.0

**Comment by epinna** [comment]
That's strange, it should work. Are you sure that the cookie does refers to a currently active HTTP session?

**Comment by plerixus** [comment]
Hello,
I have ran into the same issue, except there are multiple cookies used when logging into the site.
I have also tried to change user agent to look like my browser.
Also when i click on the link i get to Download the file instead of previewing it.
