### ISSUE TITLE
How to resolve suexec policy violation causing error 500, in the "real" server?

### ISSUE THREAD

**Issue by Trioblack** [epinna/weevely3#41]
**When I try to run in the browser:**

_Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
....
More information about this error may be available in the server error log._

**When I try to run the terminal:**

_[-] [Channel] The remote script execution triggers an error 500, please VERIFY integrity script and sent payload correctness
[-] [Channel] The remote script execution triggers an error 500, please VERIFY integrity script and sent payload correctness
[-] [Channel] The remote script execution triggers an error 500, please VERIFY integrity script and sent payload correctness
[!] [Terminal] Backdoor communication failed: please check reachability URL and password_

** But on the local server runs fine.**

**Comment by epinna** [comment]
Hello,

If locally works fine, I guess the remote installation has somehow corrupted the uploaded PHP, or some remote configuration prevents the correct execution. Without the web server logs I've no data to understand what's the problem there. 

I close this, feel free to comment if you have more information.

**Comment by asnair** [comment]
This is happening to me as I uploaded the script into a SQL field that prepends a single SQL statement to the beginning of the script I think, which might be corrupting the file. Would there be some way to force weevely to only run PHP code within a certain file? The file itself is PHP, but there is a line at the beginning that is breaking.
