### ISSUE TITLE
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0

### ISSUE THREAD

**Issue by reversingfr** [epinna/weevely3#42]
Hi
When I  launch a command weevely, I've got this error message : 
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0

Any idea?

**Comment by epinna** [comment]
It seems like an error in your PHP config files. Did you try this [fix](http://stackoverflow.com/questions/14074101/getting-comments-starting-with-are-deprecated-message-via-cli)?

**Comment by reversingfr** [comment]
unfortunately I think I can't execute the command : 
find /etc/php5/cli/conf.d/ -name "*.ini" -exec sed -i -re 's/^(\s*)#(.*)/\1;\2/g' {} \;
with weevely, because of this PHP error

**Comment by epinna** [comment]
It's not a weevely error, it's an error in your PHP configuration, triggered because the local php binary is called to minify the sent PHP code.

You should run the proposed fix in your own shell, not in weevely.

**Comment by reversingfr** [comment]
thank you !
