### ISSUE TITLE
Question about generate 

### ISSUE THREAD

**Issue by 631068264** [epinna/weevely3#43]
After I run `weevely generate 123456 wee.php`,I can`t find any **wee.php** in my Kali Linux.

`Generated backdoor with password '123456' in 'wee.php' of 1456 byte size.`

So where`s the **wee.php**

**Comment by epinna** [comment]
You should find it in your current folder, but I'm not sure which version and how it's installed in Kali. To be safe just use an absolute path e.g. `weevely generate 123456 /tmp/wee.php`.
