### ISSUE TITLE
Weevely Temp folder

### ISSUE THREAD

**Issue by LordHultonus** [epinna/weevely3#44]
Hey, Im using windows python2.7 to run weevely.
I tried to use NANO but my PC denied access to .temp folder where edited files are temporary kept. Any ideas how to fix that? I run command line in Admin mode of course.

**Comment by epinna** [comment]
Hi,

Sorry for the late answer. Since I don't have currently a Windows box to riproduce the error, I'll keep this open in order to look on this issue later. Please consider Windows as not officially supported OS - a Linux virtual machine or OS X are supported instead.

**Comment by LordHultonus** [comment]
Sure, would be great since I have no idea if there's any way to fix this error. Apparently program has no permissions to modify somenthing in temp folder...
