### ISSUE TITLE
error and missing options

### ISSUE THREAD

**Issue by devrajashwin** [epinna/weevely3#45]
hey hi sir ,
i found some errors and missing some option as i seen in readme file 

[+] weevely 3.3.1
[!] Error: too few arguments

[+] Run terminal to the target
    weevely <URL> <password> [cmd]

[+] Load session file
    weevely session <path> [cmd]

[+] Generate backdoor agent
    weevely generate <password> <path>

**Comment by epinna** [comment]
Hello,

Take a look at the wiki page on how to start with weevely.

https://github.com/epinna/weevely3/wiki/Install-and-first-run
