### ISSUE TITLE
error and missing options again

### ISSUE THREAD

**Issue by devrajashwin** [epinna/weevely3#46]
sir i did all the things that i found in ur link https://github.com/epinna/weevely3/wiki/Install-and-first-run
1>i am using kali rolling 
2>i have installed all thing that was described in that link , linux
3> Generated backdoor with password 'mypassword' in 'agent.php' of 1469 byte size.

every thing done but again same problem missing some argument

[+] weevely 3.3.1
[!] Error: too few arguments

[+] Run terminal to the target
    weevely <URL> <password> [cmd]

[+] Load session file
    weevely session <path> [cmd]

[+] Generate backdoor agent
    weevely generate <password> <path>

**Comment by epinna** [comment]
> Then, upload the generated agent under the target web folder. Make sure that the agent PHP script is properly exposed and executable through the web server.

Did you do this?

**Comment by devrajashwin** [comment]
sir its give me error [-][channel] The remote backdoor request triggers an error 404, check availability
[-][channel] The remote backdoor request triggers an error 404, check availability

and what about the missing arguments 
[!] Error: too few arguments

**Comment by epinna** [comment]
The prints are quite self-explaining: 

- In the first error, you're passing a URL that triggers a 404 "resource not found" error, which means you are using a wrong URL, or you didn't upload the backdoor agent, or the URL is not accessible.
- In the second error you're not calling weevely correctly, read how to use it correctly and retry.

This errors are not weevely errors, you only need to understand how to use it correctly. However this is not the right place to ask this kind of support, I suggest you to try on user forums (Kali Linux forum, for example). I close this.

**Comment by devrajashwin** [comment]
but how to upload it to trageted host ,
for example mysite.com  lets consider it,
i wanted to  upload phpfile backdoor i have created ,
how can i do that .........
