### ISSUE TITLE
Any idea this? On Kali Rolling?

### ISSUE THREAD

**Issue by alexwiththescar** [epinna/weevely3#47]
`Traceback (most recent call last):`
`  File "./weevely.py", line 98, in <module>`
  `  main(arguments)`
  `File "./weevely.py", line 38, in main`
   ` password = arguments.password`
`  File "/root/weevely3/core/sessions.py", line 223, in __init__`
   ` saved_url = sessiondb.get('url')`
`AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by epinna** [comment]
Try deleting ~/.weevely folder and run it again (backup it if you have any session you want to save).

Do you still see the error message?

**Comment by alexwiththescar** [comment]
Hi, Sorry delay. Still same, removed any trace of weevley or weevley3 on the system and re-clone from git but same error.

Any Ideas?

**Comment by epinna** [comment]
Just tried on Kali rolling, it works for me.

Are you sure you deleted the `.weevely/` (note the starting point) folder in your home directory? You have an error on session loading, it should be that.

**Comment by alexwiththescar** [comment]
Totally missed the dot. Seems spot on now. :)

Apologies

**Comment by epinna** [comment]
np :)
