### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by SweetSoul** [epinna/weevely3#48]
I'm having a network error when i try to connect to the remote backdoor.

here is the cmd i ran and the output

`sudo weevely http://#############/#######/weev.php 123`

`[+] weevely 3.2.0`

`[+] Target:	###############`
`[+] Session:	/root/.weevely/sessions/##################/weev_0.session`

`[+] Browse the filesystem or execute commands starts the connection`
`[+] to the target. Type :help for more information.`

`weevely> uname -a`
`[-][channel] Network error, unable to connect to the remote backdoor`

In addition i can say that the target is pwn with a webshell - php but when i try to backconnect there, i can't do it either.. but in both cases i don't have enought verbosity to see what's going on... 
Some thoughts?

**Comment by epinna** [comment]
You can try running

```
weevely> :set debug True 
```

And re-run your command, maybe it can help. The verbosity is increased both on screen and on the `~/.weevely/weevely.log` log file.
