### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by mehranexpert** [epinna/weevely3#51]
```
weevely> ls
sh: /bin/ls: Permission denied

$ cat 
sh: /bin/cat: Permission denied
```

but with this user i can do `ls `and other commands .

**Comment by epinna** [comment]
It's probably due to some security module like apparmor, which is configured to deny the execution of the binaries to the web server process.

You can still replace the denied binaries with the weevely modules such as `:file_ls` and `:file_read`.  Use `:help` to show the list of modules.
