### ISSUE TITLE
Meterpreter support

### ISSUE THREAD

**Issue by jvoisin** [epinna/weevely3#52]
It would be super-great to have a command like `:shell_meterpreter <ip port>` to get a connectback to a [meterpreter]( https://github.com/rapid7/metasploit-payloads ) listener.

**Comment by epinna** [comment]
This needs some knowledge of meterpreter internals and time and I don't have right now. I'll keep it open looking for some external contribution.

**Comment by jvoisin** [comment]
This was done in 0420cb4c174b78edbd675e822135bdc75ce7986a

Thank you ♥

**Comment by epinna** [comment]
:)
