### ISSUE TITLE
Use a CI system

### ISSUE THREAD

**Issue by jvoisin** [epinna/weevely3#54]
It would be great to have the testsuite run automatically on each commit/pull-request to avoid regressions, with for example [travis-ci](https://travis-ci.org): it's a simple `yaml` file with a simple syntax, and it's a free service.

**Comment by epinna** [comment]
The test suite (see [here](https://github.com/epinna/weevely3/wiki/running-the-testsuite) if you want to run it locally) is a pretty overly complex collection of tests that heavily relies on external components (e.g. webserver, file system fiddling, external website for :net_proxy testing, etc.), so I suspect that porting everything to travis-ci would take a lot of effort. 

I'll take a look at it and keep open for contribution, though. Thanks for the suggestion.

**Comment by jvoisin** [comment]
Maybe it's a good opportunity to simplify the deployment of the testsuite ;)
