### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by 404Ghost99** [epinna/weevely3#57]
Hello, i'm found this error when i'm execute: python weevely.py <URL> <password>
can u help me? thanks :smile:

Traceback (most recent call last):
  File "weevely.py", line 98, in <module>
    main(arguments)
  File "weevely.py", line 38, in main
    password = arguments.password
  File "/root/weevely3/core/sessions.py", line 223, in __init__
    saved_url = sessiondb.get('url')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by epinna** [comment]
Try deleting ".weevely" (note it starts with a dot) in your home folder and run it again (backup it if you have any session you want to save).

Do you still see the error message?

**Comment by 404Ghost99** [comment]
awesome, thanks bro fixed! :smile:
