### ISSUE TITLE
Crash in generate.py

### ISSUE THREAD

**Issue by 0x27** [epinna/weevely3#6]
Bug in generate.py as of commit 4964d6e659 (or earlier).

Traceback:
```
lsd@delerium:~/tools/weevely3$ ./generate.py password123 agent.php
Traceback (most recent call last):
  File "./generate.py", line 96, in <module>
    agent = args.agent
  File "./generate.py", line 48, in generate
    (obfuscator_path, str(e)))
core.weexceptions.FatalException: Error with obfuscator template 'bd/obfuscators/obfusc1_php.tpl': expected string or buffer
lsd@delerium:~/tools/weevely3$ 
```

**Comment by epinna** [comment]
I can't reproduce the crash on the same commit.

To make sure you have the latest mako and other libraries type:

```bash
$ sudo apt-get install python-pip libyaml-dev
$ sudo pip install prettytable Mako pyaml dateutils --upgrade
```

https://github.com/epinna/weevely3/wiki/Install-and-first-run

**Comment by 0x27** [comment]
Hmmm, this is interesting.

```
lsd@delerium:~/tools/weevely3$ python -V
Python 2.7.8
lsd@delerium:~/tools/weevely3$ sudo pip install prettytable Mako pyaml dateutils --upgrade
Requirement already up-to-date: prettytable in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: Mako in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pyaml in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: dateutils in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: MarkupSafe>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from Mako)
Requirement already up-to-date: PyYAML in /usr/local/lib/python2.7/dist-packages (from pyaml)
lsd@delerium:~/tools/weevely3$ ./generate.py password123 agent.php
Traceback (most recent call last):
  File "./generate.py", line 96, in <module>
    agent = args.agent
  File "./generate.py", line 48, in generate
    (obfuscator_path, str(e)))
core.weexceptions.FatalException: Error with obfuscator template 'bd/obfuscators/obfusc1_php.tpl': expected string or buffer
lsd@delerium:~/tools/weevely3$ 
```

**Comment by epinna** [comment]
That's odd :| Seems a variable wrongly set to non-string is handled as string in the *bd/obfuscators/obfusc1_php.tpl* Mako template. Unfortunately I can't reproduce it, see if you can debug it a bit to find more info.

**Comment by garlix** [comment]
Hi! I'm running on linux mint 17 the same command as 0x27 and I receive the same error
I have installed a new fresh version of pip:
```
$ pip list
apturl (0.4.1ubuntu4)
BeautifulSoup (3.2.1)
dateutils (0.6.6)
Mako (1.0.1)
MarkupSafe (0.23)
pip (6.0.7)
prettytable (0.7.2)
pyaml (14.12.10)
python-dateutil (2.4.0)
pytz (2014.10)
PyYAML (3.11)
requests (2.5.1)
setuptools (3.3)
six (1.9.0)
tortoisehg (2.10)
vboxapi (1.0)
$ python -V
Python 2.7.6
```
As you can see I successfully and diligently follow the tutorial instructions. But when I type
```
$python weevely.py generate asdasd123 agent.php
[!][weevely] Exiting: Error with obfuscator template '<path-to-weevely3>/bd/obfuscators/obfusc1_php.tpl': expected string or buffer
```
What can I do?

**Comment by epinna** [comment]
I double checked updating Mako to your version, but still I can't reproduce the error. I'll download Linux Mint 17 and retry on your environment.

**Comment by garlix** [comment]
Hi! Thanks a lot for your reply. If you want I'd be happy to help you with some further investigations... Just tell me what to do.

**Comment by epinna** [comment]
We can try quickly in this way, open `core/generate.py` and add at to the line 38 the statement `raise`, in this way:

```
    except Exception as e:
        raise
        raise FatalException(
            messages.generate.error_obfuscator_template_s_s %
            (obfuscator_path, str(e)))
```

And than re-run the command. Could you quickly check and past to me the exception print?

**Comment by garlix** [comment]
As soon as I get back home I'll give it a try and I let you know.
Il 02/feb/2015 16:55 "Emilio" <notifications@github.com> ha scritto:

We can try quickly in this way, open core/generate.py and add at to the
line 38 the statement raise, in this way:

    except Exception as e:
        raise
        raise FatalException(
            messages.generate.error_obfuscator_template_s_s %
            (obfuscator_path, str(e)))

And than re-run the command. Could you quickly check and past to me the
exception print?

—
Reply to this email directly or view it on GitHub
<https://github.com/epinna/weevely3/issues/6#issuecomment-72480665>.

**Comment by garlix** [comment]
This is the full *stack trace* I obtained running the same command with your modifications:
```
$ python weevely.py generate asdasd agent.php
Traceback (most recent call last):
  File "weevely.py", line 92, in <module>
    main(arguments)
  File "weevely.py", line 23, in main
    agent = arguments.agent
  File "/home/andrea/Scrivania/weevely3/core/generate.py", line 36, in generate
    obfuscated = obfuscator_template.render(agent=agent)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "_home_andrea_Scrivania_weevely3_bd_obfuscators_obfusc1_php_tpl", line 54, in render_body
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```
Hope it helps

**Comment by epinna** [comment]
I've no idea, I'll download Mint tomorrow and double check this. Thanks for the help.

**Comment by garlix** [comment]
Thank you for your kindness

**Comment by epinna** [comment]
Please pull and retry now.

**Comment by garlix** [comment]
Yes! Now it works! Great! Thank you very much

**Comment by 0x27** [comment]
Also can confirm it works now across 2 boxes it was breaking on :)

**Comment by epinna** [comment]
Good to heard :)
