### ISSUE TITLE
AttributeError: 'module' object has no attribute 'create_default_context'

### ISSUE THREAD

**Issue by 404Ghost99** [epinna/weevely3#60]
i got this error when i'm excecute this command >> python weevely URL password
i'm using python2.7.6 in ubuntu 14.04, and i've deleted file .weevely in root dir 
can u help me please :smiley:

![xxxxxxxxx](https://cloud.githubusercontent.com/assets/8980647/22406259/66e59a5e-e682-11e6-84f4-675d5e331726.jpg)

**Comment by epinna** [comment]
It is because of the default python (2.7.6) version ubuntu is using. Upgrading ubuntu to 15.10 which in turn upgraded the python version to 2.7.10 resolved it.

**Comment by 404Ghost99** [comment]
how about this
![sc](https://cloud.githubusercontent.com/assets/8980647/22406587/06d0c156-e688-11e6-955a-5353710ce1b7.jpg)

**Comment by epinna** [comment]
Now you upgraded python, you have to install the dependencies with `pip -r requirements.txt` making sure it's pip for python 2.7.13. See here https://github.com/epinna/weevely3/wiki/Install-and-first-run .
