### ISSUE TITLE
terminal , password or URL error 

### ISSUE THREAD

**Issue by jcpatelbugfindrer** [epinna/weevely3#61]
after upload file when ever i run the file from wevely and try to give any command on that connection i am always getting this kind of thing i don't know why ?

weevely> whoami
weevely> [!][terminal] Backdoor communication failed, check URL availability and password

**Comment by epinna** [comment]
Make sure you have uploaded the PHP agent to the target, check that the agent URL is reachable from your box without any error, and double-check the URL and password is correct. You can try to debug the behaviour setting

`:set debug True`

On the weevely terminal
