### ISSUE TITLE
bug on module net phpproxy

### ISSUE THREAD

**Issue by torquez** [epinna/weevely3#64]
net_phpproxy can't upload poxy.php to server because module upload2web doesn't have arg -rname 

![module_phpproxy](https://cloud.githubusercontent.com/assets/28835153/26281479/7fe50922-3e2a-11e7-9f2b-14675b075dc8.png)

change line 37 to  os.path.join(self.args['rpath'], self.args['rname'])
and remove line 38
![module_phpproxy_fix](https://cloud.githubusercontent.com/assets/28835153/26281585/fe885902-3e2d-11e7-98ab-7112da7c199f.png)

**Comment by epinna** [comment]
Thanks, well spotted.
