### ISSUE TITLE
POST instead of stegareferrer?

### ISSUE THREAD

**Issue by skftn** [epinna/weevely3#67]
I can remember weevely delivering commands via POST as opposed to the `stegareferrer` that's being used right now. Is that true?

Also, shouldn't POST be better because the content body doesn't show up in webserver logs?

**Comment by epinna** [comment]
It never used POST request, but implementing such a channel should be pretty easy. At that time I preferred this sort of steganography within the Refer header, but could make sense to implement an alternative POST channel.

**Comment by epinna** [comment]
I've implemented the POST based channel wich is now default.

**Comment by skftn** [comment]
nice!
