### ISSUE TITLE
[Feature Request] Simultaneous Backdoor Management

### ISSUE THREAD

**Issue by zero77** [epinna/weevely3#69]
At the moment weevely3 is a very slow because, if you have multiple backdoors you have to do everything one by one which takes ages.

For example, if you want to install or use a proxy, send commands, get system or country info or even check if they are still active, you have to do it individually.

So, can you please add support for managing multiple backdoors at once, maybe by storing them in a text file although, there may be a more efficient way.

Thanks 

p.s.
I can’t code but, if you need a help in any other way let me know.

**Comment by epinna** [comment]
I won't add that it's over the intended functionalities. Still, Weevely you can easily write a shell script to run multiple commands on multiple sessions.
