### ISSUE TITLE
readline module error on Mac OS (core/terminal.py)

### ISSUE THREAD

**Issue by RickGray** [epinna/weevely3#7]
I run weevely3 on Mac OS, but some errors happened.

The dependent libraries of readline module in Mac OS and Linux, is defferent. There is the official description of the [readline](https://pypi.python.org/pypi/readline) module.

I think this information should be explained in the Wiki. 

:)

**Comment by epinna** [comment]
Thank you for the info. Is the only missing library?

Is there a simple way to install readline on macos (maybe installing ‘readline‘ or ‘pyreadline‘ with pip?) in order to write a tutorial which is also valid for macos? Thanks in advance.

**Comment by RickGray** [comment]
Yeah, currently i found only this problem.

To solve this problem there are two steps:

1. Install the [libedit](http://thrysoee.dk/editline/).
2. Install readline module from [https://pypi.python.org/pypi/readline](https://pypi.python.org/pypi/readline). 

I download the [readline-6.2.4.1-py2.7-macosx-10.7-intel.egg](https://pypi.python.org/packages/2.7/r/readline/readline-6.2.4.1-py2.7-macosx-10.7-intel.egg#md5=6ede61046a61219a6d97c44a75853c23) from download page and uncompress it, then use `easy_install` to install.

**Comment by epinna** [comment]
I updated the wiki [page](epinna/weevely3/wiki/Install-and-first-run) with your information, thank you again.
