### ISSUE TITLE
Can weevely connect to a .jpg extension?

### ISSUE THREAD

**Issue by 8ofl31** [epinna/weevely3#70]
Hey, can weevely connect to a php script with an extension other than "php"? I feel I've seen a tutorial some time ago where it connected to a .txt and/or a php.jpg. The website I'm pentesting renames the uploaded files so double extensions are out of the question.

> $ curl http://website.com/images/photo.jpg

Doing this shows the raw weevely php code is unmodified, so I know the file uploaded correctly. Can weevely connect to a .jpg that's actually php?

With debugging enabled I get this error:

    [D][php] PHP setup failed
    [!][Terminal] Backdoor communication failed: please check URL reachability and password.

And nothing else in the log. I'm using weevely v3.2 in Kali. Any help with this would be wonderful.

**Comment by epinna** [comment]
It depends on how the web server interprets the .jpg files. If it doesn't interpret them as PHP, weevely won't work.

Implying it's apache, your webserver would need a configuration like

```
<FilesMatch "\.jpg$">
    SetHandler application/x-httpd-php
</FilesMatch>
```

To tell him to execute .jpg files as PHP. In other words, a properly configured webserver won't allow you to execute any code in images.
