### ISSUE TITLE
Weevely and custom cookies

### ISSUE THREAD

**Issue by plerixus** [epinna/weevely3#71]
Hello,
I have ran into the same issue as issue #38.
(https://github.com/epinna/weevely3/issues/38)

There is weevely uploaded to the site which i can only access when i am logged in (I am able to login normally)
Except there are multiple cookies used when logging into the site.
I have also tried to change user agent to look like my browser.
Also when i click on the link i get to Download the file instead of previewing it.

**Comment by epinna** [comment]
It's not enough information to debug your issue. 

Try `:set debug True` and run `tail -f ~/.weevely/weevely.log` to keep track of the exchanged data to understand if weevely client is sending the data you're expecting.

**Comment by plerixus** [comment]
I ended up getting:
[D][php] PHP setup failed 
[!][terminal] Backdoor communication failed: please check URL reachability and password
weevely>
