### ISSUE TITLE
sql_console password include special characters

### ISSUE THREAD

**Issue by bstaint** [epinna/weevely3#73]
Password such as  `test$abc`, will 
> Access denied for user 'root'@'localhost' (using password: YES) 

Replace quotes can fixed, `weevely3/modules/sql/console.py` Line: 26:

```
"${passwd}" => '${passwd}'
```
or type `test\\$abc`

**Comment by epinna** [comment]
You're right, I'll fix it soon. Thanks for the tip-off.
