### ISSUE TITLE
[-][channel] The request triggers the error 504, please verify running code

### ISSUE THREAD

**Issue by 7yaX** [epinna/weevely3#79]
What should i do?
'''
web15@server2.surakarta.go.id:/var/www/ $ chmod +x file
web15@server2.surakarta.go.id:/var/www/ $ ./file
[-][channel] The request triggers the error 504, please verify running code
web15@server2.surakarta.go.id:/var/www/ $ 
'''

**Comment by epinna** [comment]
It seems the command execution is taking too much and triggers the PHP timeout. You can try

1. Manually run PHP code to override timeout settings before the execution i.e. `:shell_php 'set_time_limit(0);system("./file");'`
2. Try running it as background process, sometime redirecting stdout/stdin/stderr helps the file execution is not killed by PHP i.e. running `./file & </dev/null &>/tmp/logfile`

This is not an issue related to weevely, though, I'm closing this.
