### ISSUE TITLE
[improvement request] provide a manpage/better help output

### ISSUE THREAD

**Issue by samueloph** [epinna/weevely3#84]
Hello, i intend to package weevely for Debian, one thing i noted during working on it is that weevely does not provide a manpage, on this cases i usually generate one using help2man, but help's output of weevely does not contain much info.

I understand that the wiki contains detailed use cases and examples, and would be nice to have that (some of that at least) together with the source code of weevely in the form of a manpage or the help output.

I understand this kind of work may be boring and people might not be interested on doing it, that's why i thought about leaving this issue, just in case anyone wants to contribute.

**Comment by epinna** [comment]
Hello Samuel,

That would be a great improvement, I will work on it. Thanks for your help.

**Comment by epinna** [comment]
What about using the README markdown? 

I slightly changed it to feel a bit more like a manpage-ish, so if you strip out the links, replace `usage` with `synopsis`, and convert it using `pandoc README.md -s -t man`, it ends up like the attached groff file.

[weevely.txt](https://github.com/epinna/weevely3/files/2091471/weevely.txt)

Not sure how strict are the manpage format requirements, but seems a good starting point.

**Comment by samueloph** [comment]
@epinna thanks, i'll work on that. I suggest leaving this issue open until i (or someone else) submit a manpage.
