### ISSUE TITLE
Error running weevely

### ISSUE THREAD

**Issue by cartagenae** [epinna/weevely3#85]
Unable to run ./weevely generate [password] [directory]/file.php

I get an error:
    "env: python2: No such file or directory"

<img width="571" alt="screen shot 2018-06-19 at 4 23 59 am" src="https://user-images.githubusercontent.com/6395465/41594579-a7793722-7378-11e8-90bb-7a192938114d.png">

**Comment by epinna** [comment]
You need Python >= 2.7.10 installed on the system, please follow the install guide on the [wiki](https://github.com/epinna/weevely3/wiki/Install).

**Comment by cartagenae** [comment]
I'm still receiving the same error.

**Comment by cartagenae** [comment]
<img width="1280" alt="screen shot 2018-06-19 at 6 48 53 pm" src="https://user-images.githubusercontent.com/6395465/41633021-846c5efc-73f1-11e8-9847-96ba20a99cf8.png">

**Comment by cartagenae** [comment]
![highlighted_screen_shot](https://user-images.githubusercontent.com/6395465/41633238-b14fb6ac-73f2-11e8-886f-4f45703328fa.png)

**Comment by epinna** [comment]
I looked at the Macport `python27` install [script](https://github.com/macports/macports-ports/blob/master/lang/python27/Portfile), it seems you need to run the following command to make it the default 'python2' command:

```
sudo port select --set python2
```

Let me know if it works I add macport install on the wiki. Thanks!

**Comment by cartagenae** [comment]
<img width="570" alt="screen shot 2018-06-20 at 12 58 37 am" src="https://user-images.githubusercontent.com/6395465/41645216-24137d04-7425-11e8-8482-f01dd9f06325.png">

No. Still no luck

**Comment by epinna** [comment]
It's some Macports quirk I can't debug since I don't use it, try to search on the internet some solution like like [this](https://stackoverflow.com/questions/8201760/how-to-macports-select-python) to resolve the issue.

**Comment by cartagenae** [comment]
Definitely. Will do. I do not know what the problem here but whatever it is, if it doesn't work on mac, I'll just continue using it on my Linux distribution instead... Thank you so much for your time. You're awesome.

**Comment by epinna** [comment]
I'm pretty sure that creating a sym link to your official Python binary with something like `sudo ln -s /opt/local/bin/python /opt/local/bin/python2` (this is just an example, I'm not sure which where Macports installs the binaries) will solve the issue, but let me  know if you find a cleaner solution and I'll add it to the wiki.

Thanks!

**Comment by Pradeepgm11** [comment]
help me to resolve this error

weevely generate 123456 shell2.php
Traceback (most recent call last):
  File "/usr/bin/weevely", line 2, in <module>
    from core.terminal import Terminal
  File "/usr/share/weevely/core/terminal.py", line 6, in <module>
    from core.module import Status
  File "/usr/share/weevely/core/module.py", line 14, in <module>
    from core.vectorlist import VectorList
  File "/usr/share/weevely/core/vectorlist.py", line 15, in <module>
    from core.vectors import Os
  File "/usr/share/weevely/core/vectors.py", line 11, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'

**Comment by shawky1352001** [comment]
Traceback (most recent call last):
  File "/usr/bin/weevely", line 2, in <module>
    from core.terminal import Terminal
  File "/usr/share/weevely/core/terminal.py", line 6, in <module>
    from core.module import Status
  File "/usr/share/weevely/core/module.py", line 14, in <module>
    from core.vectorlist import VectorList
  File "/usr/share/weevely/core/vectorlist.py", line 15, in <module>
    from core.vectors import Os
  File "/usr/share/weevely/core/vectors.py", line 11, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'


i need help to solve this error

**Comment by francismboya** [comment]
> Traceback (most recent call last):
> File "/usr/bin/weevely", line 2, in
> from core.terminal import Terminal
> File "/usr/share/weevely/core/terminal.py", line 6, in
> from core.module import Status
> File "/usr/share/weevely/core/module.py", line 14, in
> from core.vectorlist import VectorList
> File "/usr/share/weevely/core/vectorlist.py", line 15, in
> from core.vectors import Os
> File "/usr/share/weevely/core/vectors.py", line 11, in
> from mako.template import Template
> ModuleNotFoundError: No module named 'mako'
> 
> i need help to solve this error

install mako using

pip3 install mako
