### ISSUE TITLE
'generate' command to honor current path (no need to absolute path of file)

### ISSUE THREAD

**Issue by samueloph** [epinna/weevely3#88]
Currently, when running weevely generate password something.php, the file something.php always goes to "/usr/share/weevely/something.php" (because weevely is instaled there). This leads to a problem where users needs to be root if they don't pass the absolute path of the file.

That is, users should always pass the absolute path of the file if they don't want it together with the weevely executable and/or they are not root. I think it is preferable to honor the current path of the shell running weevely instead.

Thanks.

**Comment by epinna** [comment]
I think this is a problem of an old version of weevely (the one actually included in Kali, unfortunately). If I try on the current version I see it behaves correctly:

```
$ ./weevely3/weevely.py  generate asd asd
Generated 'asd' with password 'asd' of 769 byte size.
$ ls asd
asd
$
```

The file is created in the current folder as expected. Am I missing something?

**Comment by samueloph** [comment]
@epinna oh, yeah, i just realized Kali is shipping 3.2, i'll update the debian package to 3.6 (kali should get that version too).

Thanks

**Comment by epinna** [comment]
Great, thanks.
