### ISSUE TITLE
audit_etcpasswd does not work!

### ISSUE THREAD

**Issue by imjdl** [epinna/weevely3#93]
Hello Emilio, I read the description about [audit_etcpasswd](https://github.com/epinna/weevely3/wiki/Get-etc-passwd-content-with-no-read-access).I tested on my own Ubuntu but it didn't work.
My configuration is as follows：
Ubuntu18.0.4
PHP 5.6.37
php.ini:
![](http://ovjdtotu0.bkt.clouddn.com/Selection_002.png)
operation result
![](http://ovjdtotu0.bkt.clouddn.com/Selection_003.png)
I am very confused. Is there something wrong with me? Please help me, thank you (from Google Translate)

**Comment by epinna** [comment]
Note that those `php.ini` setting shown [here](https://github.com/epinna/weevely3/wiki/Get-etc-passwd-content-with-no-read-access) is just an example on which PHP restrictions the module should still work with. You don't need it to set them.

Still seems something is going wrong, so please run `:set debug True` and try it again, and attach the screenshot here.

**Comment by ViCrack** [comment]
猜测可以试着加个参数:audit_etcpasswd -vector=posix_getpwuid，
让weevely的audit_etcpasswd模块优先使用posix_getpwuid等php方法枚举uid的信息，构造出etc/passwd类似的内容。不知道是否因为choices参数没法初始化一个默认值，导致posix_getpwuid没有执行


![default](https://user-images.githubusercontent.com/18179821/44625024-c8f7af80-a930-11e8-97e9-7aabf4231aca.png)

**Comment by imjdl** [comment]
@ViCrack 是的，加一个-vector=posix_getpwuid参数是可以执行的，weevely我也是刚用，源码也不熟悉，现在我正准备看一下源码。谢谢你。

**Comment by imjdl** [comment]
@epinna I used @ViCrack method, and audit_etcpasswd can be used. But I don't know why, now I am trying to read the source code. thank you.
![](http://ovjdtotu0.bkt.clouddn.com/Selection_008.png)

**Comment by epinna** [comment]
Glad it worked, it also was an error on Weevely managing the vector argument. Now it should sort the vector out even if you don't specify it with `-vector`, please pull it again and try it if you can. Thanks.

**Comment by imjdl** [comment]
I have tried it and can use it now.
