### ISSUE TITLE
cannot execute sql

### ISSUE THREAD

**Issue by neal1991** [epinna/weevely3#94]
I have uploaded the backdoor php file to the target machine, and I can login the database of mysql. I can execute commands like；

```sql
show databases;
show tables in ctf
select table_name from information_schema.tables where table_schema = 'ctf';
```

But  I cannot execute sql command, the database name is `ctf` and table name is `flag`. However, when I execute the command `select * from flag`.

The result is : ` No data returned Check credentials and DB availability`

Obviously, the database and table name can be obtained. But sql command cannot be executed correctly.

**Comment by epinna** [comment]
What if you execute `select * from ctf.flag`? Weevely SQL client doesn't keep a state so commands such as `use <database>` don't work and you have to always use the `databasename.tablename` format.

**Comment by neal1991** [comment]
@epinna Thank u very muck!!! It works. Why I have not thought about this! Thanks!
