### ISSUE TITLE
Expected URL format error

### ISSUE THREAD

**Issue by zyjsuper** [epinna/weevely3#97]
when i run command 'weevely generate.htaccess password ./.htaccess'
it received a error like below:
[!][weevely] Exiting: Expected URL format 'http(s)://host/agent.php'

How to explain this messge,
look forward to your reply,thanks a lot.

**Comment by epinna** [comment]
The command generate.htaccess simply does not exist. You could generate a backdoored .htaccess in old versions like weevely 0.7, but it is not supported anymore.
