### ISSUE TITLE
Path behavior when generating shell

### ISSUE THREAD

**Issue by noraj** [epinna/weevely3#98]
I have `/bin/weevely` containing:

```bash
#!/bin/sh
cd /usr/share/weevely
exec python2 weevely.py "${@}"
```

And `/usr/share/weevely` containing the up-to-date clone of teh repository.

Whene generating a shell with a relative path like that `weevely generate password shell.php` or even `weevely generate password ./shell.php`, weevely try to write `/usr/share/weevely/shell.php` instead of the expected `$(pwd)/shell.php`.

https://github.com/epinna/weevely3/blob/master/weevely.py#L26

https://github.com/epinna/weevely3/blob/master/core/generate.py#L51

In my case I got `[!][weevely] Exiting: Error creating file './shell.php': [Errno 13] Permission denied: './shell.php'` because `/usr/share/weevely/` is own by root and write protected. So i'm forced to use sudo to generate the shell or to use an absolut PATH.

**Comment by epinna** [comment]
Well, if you change the current folder to `/usr/share/weevely/` before executing it, how can weevely know your real folder? :) It will just try to generate it under the current one, which is `/usr/share/weevely/`, failing.

Can't you just rewrite `/bin/weevely` as

```
#!/bin/sh
exec python2 /usr/share/weevely/weevely.py "${@}"
```

? Let me know if it makes sense.

**Comment by noraj** [comment]
You're right, I didn't think about it.
